config/routes.rb
Rails.application.routes.draw do
  root 'throws#new'
  
  resources :throws, only: [:new, :create]
end

app/models/throw.rb
# This class represents a throw.
class Throw
  # @!attribute sign
  # The sign that was selected by the user.
  # @return [String]
  attr_reader :sign

  # This method creates a new throw.
  #
  # @param [String] sign
  # The sign selected by the user.
  #
  # @return [Throw]
  def initialize(sign)
    @sign = sign
  end

  # This method returns the result.
  #
  # @return [Symbol]
  def result
    if random == sign
      :tie
    elsif Throw.winners.include?([sign, random])
      :win
    else
      :lose
    end
  end

  # This method gets a random pick.
  #
  # @return [String]
  def random
    @random ||= Throw.signs.shuffle.first
  end

  # This method gets all the signs that are available.
  #
  # @return [Array]
  def self.signs
    %w(rock paper scissors)
  end

  # This method gets all the winner combinations.
  #
  # @return [Array<Array>]
  def self.winners
    [
      ['rock', 'scissors'],
      ['scissors', 'paper'],
      ['paper', 'rock']
    ]
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/throws_controller.rb
class ThrowsController < ApplicationController
  # @!group Exposures

  # @!attribute _throw
  # The current throw.
  # @return [Throw]
  expose(:_throw) { Throw.new(params[:sign]) }

  # @!group Actions

  # This action displays a form for selecting a sign to throw.
  #
  # @return [Action]
  # @render new
  def new
  end

  # This action throws a sign and determines if the user has won.
  #
  # @return [Action]
  # @render create
  def create
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/throws_helper.rb
module ThrowsHelper
end

app/views/layouts/application.html.haml
%html
  %head
    %title Rock Paper Scissors
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  %body
    %nav.navbar.navbar-default{role: 'navigation'}
      .container-fluid
        .navbar-header
          %h1 Rock Paper Scissors

    .container-fluid
      = yield

app/views/throws/create.html.haml
- case _throw.result
- when :win
  .alert.alert-success You have won!
- when :tie
  .alert.alert-warning It was a tie.
- when :lose
  .alert.alert-danger Please try again.

%p
  Computer pick:
  %strong= _throw.random
  %br
  Your pick:
  %strong= _throw.sign

%p
  = link_to 'New game', new_throw_path, class: 'btn btn-default'

app/views/throws/new.html.haml
= form_tag throws_path do
  .form-group
    = select_tag :sign, options_for_select(Throw.signs), prompt: 'Select sign', class: 'form-control'

  .form-actions
    = submit_tag 'Throw', class: 'btn btn-primary'